### ISSUE TITLE
Problems serving jekyll

### ISSUE THREAD

**Issue by wilkohardenberg** [minicomp/wax#10]
I realise this may not an issue depending from minicomp/wax, but I haven't been able to serve jekyll using the bundle exec jekyll serve command. I get the following:

```
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/uri.rb:106:in `require': /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/uri/generic.rb:212: syntax error, unexpected '.' (SyntaxError)
      @scheme&.freeze
               ^
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/uri/generic.rb:335: syntax error, unexpected '.'
      @scheme = v&.downcase
                   ^
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/uri/generic.rb:1320: syntax error, unexpected '.'
      if path&.empty?
               ^
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/uri/generic.rb:1563: syntax error, unexpected keyword_end, expecting end-of-input
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/uri.rb:106:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems/specification.rb:18:in `require'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems/specification.rb:18:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems.rb:1376:in `require'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems.rb:1376:in `<module:Gem>'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems.rb:117:in `<top (required)>'
	from <internal:gem_prelude>:1:in `require'
	from <internal:gem_prelude>:1:in `<compiled>'
```
Any idea what's going on or where I can start looking for a solution? I never had problems previously serving jekyll without bundler for my non-minicomp website.

Cheers,
Wilko

**Comment by mnyrop** [comment]
Hi @wilkohardenberg, since wax doesn't use any plugins and its `wax_tasks` features are separate from the `jekyll build/serve` commands, I'm pretty sure it's not a wax issue. However, if you can reproduce the problem on a CI platform (like [Travis](https://travis-ci.org/) or [Circle](https://circleci.com/)) I'd be happy to take a peek!

-Marii
