### ISSUE TITLE
WaxTasks::Error::InvalidCollection

### ISSUE THREAD

**Issue by edsu** [minicomp/wax#43]
When I run `wax:derivatives:simple ` it looks like everything works but no additional data is written to my csv:

```
kaizen:cybermountain edsu$ bundle exec rake wax:derivatives:simple cybermountain
Writing image derivative info ./_data/metadata.csv.
```

When running with --trace you can see that there it is encountering an error `WaxTasks::Error::InvalidCollection: Cannot load collection config for wax:derivatives:simple`.

```
kaizen:cybermountain edsu$ bundle exec rake --trace wax:derivatives:simple cybermountain
** Invoke wax:derivatives:simple (first_time)
** Execute wax:derivatives:simple
rake aborted!
WaxTasks::Error::InvalidCollection: Cannot load collection config for wax:derivatives:simple.
key not found: "wax:derivatives:simple"
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/collection.rb:32:in `rescue in config'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/collection.rb:30:in `config'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/collection.rb:23:in `initialize'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/image_collection.rb:17:in `initialize'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/task_runner.rb:108:in `new'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/task_runner.rb:108:in `block in derivatives_simple'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/task_runner.rb:107:in `each'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/task_runner.rb:107:in `derivatives_simple'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/tasks/derivatives_simple.rake:10:in `block (3 levels) in <top (required)>'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/edsu/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/edsu/.rvm/gems/ruby-2.4.1/bin/rake:23:in `load'
/Users/edsu/.rvm/gems/ruby-2.4.1/bin/rake:23:in `<main>'
/Users/edsu/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/edsu/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
KeyError: key not found: "wax:derivatives:simple"
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/collection.rb:30:in `fetch'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/collection.rb:30:in `config'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/collection.rb:23:in `initialize'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/image_collection.rb:17:in `initialize'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/task_runner.rb:108:in `new'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/task_runner.rb:108:in `block in derivatives_simple'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/task_runner.rb:107:in `each'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/wax_tasks/task_runner.rb:107:in `derivatives_simple'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/wax_tasks-1.0.0.pre.beta/lib/tasks/derivatives_simple.rake:10:in `block (3 levels) in <top (required)>'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/edsu/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/Users/edsu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/edsu/.rvm/gems/ruby-2.4.1/bin/rake:23:in `load'
/Users/edsu/.rvm/gems/ruby-2.4.1/bin/rake:23:in `<main>'
/Users/edsu/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/edsu/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => wax:derivatives:simple
```

I am using the v1.0.0 branch on minicomp/wax and here is a list of my installed gems:

```
kaizen:cybermountain edsu$ bundle list
Gems included by the bundle:
  * activesupport (5.2.3)
  * addressable (2.6.0)
  * bundler (2.0.1)
  * colorator (1.1.0)
  * colorize (0.8.1)
  * concurrent-ruby (1.1.5)
  * em-websocket (0.5.1)
  * ethon (0.12.0)
  * eventmachine (1.2.7)
  * ffi (1.10.0)
  * forwardable-extended (2.6.0)
  * html-proofer (3.10.2)
  * http_parser.rb (0.6.0)
  * i18n (0.9.5)
  * jekyll (3.8.5)
  * jekyll-sass-converter (1.5.2)
  * jekyll-watch (2.2.1)
  * kramdown (1.17.0)
  * liquid (4.0.3)
  * listen (3.1.5)
  * mercenary (0.3.6)
  * mini_magick (4.9.3)
  * mini_portile2 (2.4.0)
  * minitest (5.11.3)
  * nokogiri (1.10.3)
  * parallel (1.17.0)
  * pathutil (0.16.2)
  * public_suffix (3.0.3)
  * rake (12.3.2)
  * rb-fsevent (0.10.3)
  * rb-inotify (0.10.0)
  * rouge (3.3.0)
  * ruby_dep (1.5.0)
  * safe_yaml (1.0.5)
  * sass (3.7.4)
  * sass-listen (4.0.0)
  * thread_safe (0.3.6)
  * typhoeus (1.3.1)
  * tzinfo (1.2.5)
  * wax_iiif (0.1.0)
  * wax_tasks (1.0.0.pre.beta)
  * wax_theme (1.0.0)
  * yell (2.1.0)
```

**Comment by edsu** [comment]
Here's the config, in case it is useful to see:

https://gist.github.com/edsu/992c50f13d477e05aa403a00993c9928

**Comment by mnyrop** [comment]
Closing bc stale; feel free to reopen with additional info if needed!
